apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-manage-client
  namespace: socialflow
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      types {
        application/wasm wasm;
      }
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$request_time] $time_local [$upstream_response_time] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      gzip  on;
      gzip_min_length  1k;
      gzip_buffers     4 16k;
      gzip_http_version 1.1;
      gzip_comp_level 9;
      gzip_types       text/plain application/x-javascript text/css application/xml text/javascript application/x-httpd-php application/javascript application/json application/wasm;
      gzip_disable "MSIE [1-6]\.";
      gzip_vary on;

      client_max_body_size 300m;

      include /etc/nginx/conf.d/*.conf;
    }
  proxy.conf: |-
    server {
      listen 80;
      server_name localhost;

      location / {
        root /temp/dist;
        index index.html;
      }

      # 反向代理配置
      location /qa-api/ {
        proxy_pass https://manage.sf.lightai.cn/
      }

      error_page 404 /404.html;
    }
